apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: hotel-booking
  labels:
    app: react-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: react-frontend
          image: REPOSITORY/IMAGE_NAME:TAG
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
