name: Deploy React App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/hotel-booking

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:latest

      - name: Deploy Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/hotel-booking
            docker pull $IMAGE_NAME:latest

            docker rm -f react-frontend || true

            docker run -d \
              --name react-frontend \
              --network web \
              -l traefik.enable=true \
              -l traefik.http.routers.react.rule=Host(\`hotel-booking.molika.app\`) \
              -l traefik.http.routers.react.entrypoints=websecure \
              -l traefik.http.routers.react.tls.certresolver=le \
              $IMAGE_NAME:latest
              